#' Presentation Template
#' 
#' Generate a presentation template to increase efficiency.  This is a lighter 
#' weight version of \code{\link[reports]{new_report}}.
#' 
#' @param presentation A character vector of length two or one: (1) the main directory 
#' name and (2) sub directory names (i.e., all the file contents will be 
#' imprinted with this name). If the length of \code{report} is one this name 
#' will be used as the main directory name and all sub directories and files.
#' @param type A vector of the file format types.  Any combination of the following: 
#' \code{rnw}, \code{rmd} or \code{pptx}.  \code{rnw} corresponds to a beamer slides 
#' (.Rnw file), \code{rmd}  corresponds to a html5 (compliments of slidify) slides 
#' (.Rnwd file) and \code{docx} corresponds to PowerPoint slides (.pptx file).
#' @param theme \href{http://deic.uab.es/~iblanes/beamer_gallery/index_by_theme.html}{Beamer theme}
#' to use.  If \code{NULL} \code{presentation} will allow the user to choose 
#' interactively.
#' @param bib.loc Optional path to a .bib resource.
#' @param name A character vector of the user's name to be used on the report.
#' @param github.user GitHub user name (character string).
#' @param sources A vector of path(s) to other scripts to be sourced in the 
#' report project upon startup (adds this location to the report project's 
#' \code{.Rprofile}).
#' @param path The path to where the project should be created.  Default is the 
#' current working directory.
#' @param slidify_clean logical.  If \code{TRUE} the PRESENTATION .Rmd file will be 
#' generated by slidify.  If \code{FALSE} the .Rmd file will be initialize with 
#' additional parameters for convenience.
#' @param \ldots Other arguments passed to \code{\link[slidify]{author}}.
#' @section Suggestion: The user may want to set \code{\link[base]{options}} for 
#' \code{bib.loc}, \code{github.user}  and \code{sources_reports} in the user's
#' primary \code{.Rprofile}:
#' \enumerate{ 
#'   \item{\bold{bib.loc} - The path to the users primary bibliography}
#'   \item{\bold{github.user} - GitHub user name}
#'   \item{\bold{sources_reports} - Path(s) to additional files/scripts that 
#'   should be included to be sourced in the project startup}
#' }
#' @return Creates a report template.
#' @seealso \code{\link[reports]{new_report}},
#' \code{\link[slidify]{author}}
#' @export
#' @import slidify
#' @examples
#' ## presentation("New")
presentation <- function(presentation = "presentation", type = c("rnw", "rmd"), 
    theme = "Madrid", bib.loc = getOption("bib.loc"), 
    name = getOption("name_reports"), github.user = getOption("github.user"), 
    sources = getOption("sources_reports"), path = getwd(), slidify_clean = FALSE, 
    ...) {
    presentation <- gsub("\\s+", "_", presentation)
    main <- head(presentation, 1)	
    presentation <- tail(presentation, 1)	
    if(file.exists(file.path(path, main))) {
        cat(paste0("\"", file.path(path, presentation), 
            "\" already exists:\nDo you want to overwrite?\n\n"))
        ans <- menu(c("Yes", "No")) 
        if (ans == "2") {
            stop("presentation aborted")
        } else {
            delete(file.path(path, presentation))
        }
    }
    if (is.null(theme) & sum(type %in% "rmd") > 0) {
        cat("Choose a theme:\n\n") 
        theme <- c(themes)[menu(c(themes))]      
    }
    suppressWarnings(invisible(dir.create(file.path(path, main),
        recursive = TRUE))) 
    x <- file.path(path, main)
    OUTLINE <- PRESENTATION <- NULL
    WD <- getwd(); on.exit(setwd(WD))
    setwd(x)   
    root2 <- system.file("extdata/docs", package = "reports")
    if (sum(type %in% "rmd") < 1) {
        y <- invisible(folder(OUTLINE, PRESENTATION))
    } else {
        y <- invisible(folder(OUTLINE))
        y[[2]] <- file.path(x, "PRESENTATION")
        suppressMessages(author(y[[2]], use_git = FALSE, open_rmd = FALSE))
        setwd(x)
        new_Rmd <- file.path(y[[2]], "index.Rmd")
        Rmd <- suppressWarnings(readLines(new_Rmd )) 
        Rmd[2] <- paste0(Rmd[2], presentation)
        if(!is.null(name)) {
            Rmd[4] <- paste0(Rmd[4], strsplit(name, "\\\\")[[1]][1])
        }
        Rmd[10] <- "mode        : selfcontained"
        Rmd[23] <- paste0("For slidify framework examples run:    \n", 
            "browseURL(\"https://github.com/ramnathv/slidifyExamples\")    \n")
        if (!slidify_clean) {
            Rmd[9] <- "widgets     : [mathjax, quiz, bootstrap]"
            piece1 <- "--- dt:10\n\n<script>\nhandleDomLoadedExtra = function(){};\n</script>\n\n"
            piece2 <- "```{r setup, include=FALSE}\n# set global chunk options\nopts_chunk$set(cache=FALSE)\n"
            piece3 <- "library(reports); library(slidify); library(knitcitations)\nBIB <- system.file(\"extdata/docs/example.bib\", package =  \"reports\") #test .bib\n"
            piece4 <- "bib <- read.bibtex(BIB)\n#\n#Reading in your own bib file:\n"
            piece5 <- "#bib <- read.bibtex(dir()[tools::file_ext(dir()) == \"bib\"][1])\n"
            piece6 <- "#cite in text using `r citet(bib[1])`\n```\n"
            piece7 <- "<style>\nbody {\n  background-color: #000;\n}\n"
            piece8 <- ".quiz-option label{\n  display: inline;\n  font-size: 1em;\n}\n"
            piece9 <- ".refs {\n  padding-left: 80px;\n  text-indent: -35px;\n}\n"
            piece10 <- "ul.nav li::before { content: \"\"; } \nul.nav li{ font-size: 18px; line-height: 24px;}\n</style>\n"
            Rmd[11] <- paste0(piece1, piece2, piece3, piece4, piece5, piece6, piece7, piece8, piece9, piece10)
            Rmd[25] <- "--- .refs\n## References\n```{r, echo=FALSE, results='asis'}\nbibliography(\"html\")\n```"
            Rmd[23] <- paste0(Rmd[23], "\n", "`r citet(bib[1])`\n\n---\n`r YT(\"kws1PX1Dw9w\")`")
        }
        cat(paste(Rmd, collapse="\n"), file = file.path(y[[2]], paste0(presentation, ".Rmd")))
        delete(new_Rmd)
    }
    cat(file = file.path(x, "TO_DO.txt"))
    cat(file = file.path(x, "NOTES.txt"))
    EXF <- "#Source the following project functions on startup"
    cat(EXF, file = file.path(x, "extra_functions.R"))
    root <- system.file("extdata/present", package = "reports")
    pdfloc <- file.path(root, "outline")
    pdfloc2 <- file.path(root, "pres")
    if(sum(type %in% c("rnw", "rmd")) > 0){
        invisible(file.copy(file.path(pdfloc, c("outline.tex", 
            "preamble.tex")), y[[1]]))   
        invisible(file.copy(file.path(pdfloc2, c("temp.Rnw")), 
            y[[2]]))  
        invisible(file.rename(file.path(y[[2]], "temp.Rnw"), 
             file.path(y[[2]], paste0(presentation, ".Rnw"))))          
    } 
    if(sum(type %in% "pptx") > 0){
        invisible(file.copy(file.path(pdfloc, c("outline.docx")), y[[1]]))  
        invisible(file.copy(file.path(pdfloc2, c("temp.pptx")), 
            y[[2]])) 
        invisible(file.rename(file.path(y[[2]], "temp.pptx"), 
             file.path(y[[2]], paste0(presentation, ".pptx"))))        
    }
    dir.create(file.path(y[[2]], "figure"), FALSE)
    rpro <- c("#Load the packages used",
        "library(reports); library(slidify); library(slidifyLibraries); library(knitr); library(knitcitations)", 
    	  "# library(pander)", "")  
    rpro2 <- c("", "#Source \"extra_functions.R\":",
        "source(file.path(getwd(), \"extra_functions.R\"))")
    rpro3 <- sources
    if (!is.null(rpro3)){
        rpro3 <- c("", "#Source these location(s):", 
            paste0("source(\"", rpro3, "\")"))
    }
    bib <- NULL  
    invisible(file.copy(file.path(root, "TEMP.txt"), x))
    invisible(file.rename(file.path(x, "TEMP.txt"), 
        file.path(x, paste0(presentation, ".Rproj"))))
    if(!is.null(bib.loc) && file.exists(bib.loc)){
        invisible(file.copy(bib.loc, y[[2]]))
        bib <- dir(y[[2]])[tools::file_ext(dir(y[[2]])) == "bib"]
        if (!is.null(getOption("bib.loc"))) {
            bibL <- paste0("options(bib.loc = \"", getOption("bib.loc"), "\")")
            rpro <- c(rpro, bibL)
        }
    }
    if (!is.null(!is.null(github.user) && file.exists(github.user))) {
        git <- paste0("options(github.user = \"", github.user, "\")")
        rpro <- c(rpro, git)
    }       
    cat(paste(c(rpro, rpro2, rpro3), collapse = "\n"), file = file.path(x, 
        ".Rprofile"))
    if (!is.null(bib.loc) && !file.exists(bib.loc)) {
        warning("bib.loc does not exist")
    }
    if (!is.null(bib) & sum(type %in% "rmd") > 0) {
        dr2 <- dir(y[[2]])
        drin2 <- dr2[tools::file_ext(dr2) %in% "Rmd"]
        temp2 <- suppressWarnings(readLines(file.path(y[[2]], drin2)))
        temp2 <- gsub("read.bibtex(.bib)", paste0("read.bibtex(\"", bib, "\")"), 
            temp2, fixed = TRUE)
        cat(paste(temp2, collapse="\n"), file=file.path(y[[2]], drin2))
    }
    if (sum(type %in% "rnw") > 0) {
        drin <- dir(y[[2]])[tools::file_ext(dir(y[[2]])) == "Rnw"]
        temp <- suppressWarnings(readLines(file.path(y[[2]], drin)))
        if (!is.null(bib)) {
            temp <- gsub("\\.bib", bib, temp)
        }
        temp <- gsub("\\\\title\\{.+?\\}", paste0("\\\\title{", gsub("_", " ", 
            presentation),"}") , temp)
        if (!is.null(name)) {
            fxbs <- gsub("\\", "\\\\", paste0("author{", name,"}"), fixed = TRUE)
            temp <- gsub("author\\{.+?\\}", fxbs , temp)
        }
        temp <- gsub("usetheme{}", paste0("usetheme{", theme, "}") , temp, 
            fixed = TRUE)
        cat(paste(temp, collapse="\n"), file=file.path(y[[2]], drin))
    }
    o <- paste0("Presentation \"", presentation, "\" created:\n", x, "\n")
    class(o) <- "reports"
    return(o)    
}
